const products = [
  {
    id: 1,
    category: "Футболки",
    name: "BASIC BLACK",
    price: 25,
    inStock: true,
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Чёрный", "Белый", "Серый"],
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500",
    description: "Классическая чёрная футболка из 100% хлопка. Идеально подходит для повседневной носки.",
    material: "100% хлопок (200g/m²)",
    care: ["Стирать при 30°C", "Не отбеливать", "Гладить при низкой температуре"],
    rating: 4.8,
    reviewsCount: 120
  },
  {
    id: 2,
    category: "Футболки",
    name: "STRIPE WHITE",
    price: 28,
    inStock: true,
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Белый", "Синий"],
    image: "https://images.unsplash.com/photo-1503341990857-48d2820aaad4?w=500",
    description: "Стильная полосатая футболка с классическим дизайном.",
    material: "100% хлопок (180g/m²)",
    care: ["Стирать при 30°C", "Вывернуть перед стиркой"],
    rating: 4.6,
    reviewsCount: 89
  },
  {
    id: 3,
    category: "Футболки",
    name: "CLASSIC GRAY",
    price: 25,
    inStock: true,
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Серый", "Чёрный"],
    image: "https://images.unsplash.com/photo-1506629082632-ffc1b02f5882?w=500",
    description: "Универсальная серая футболка для любого образа.",
    material: "100% хлопок (200g/m²)",
    care: ["Стирать при 40°C", "Не отбеливать"],
    rating: 4.7,
    reviewsCount: 145
  },
  {
    id: 4,
    category: "Рубашки",
    name: "OXFORD BLUE",
    price: 35,
    inStock: true,
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Синий", "Белый"],
    image: "https://images.unsplash.com/photo-1598033129519-9ff10cb7f9e7?w=500",
    description: "Классическая оксфордская рубашка с пуговицами.",
    material: "100% хлопок",
    care: ["Стирать при 30°C", "Гладить при средней температуре"],
    rating: 4.9,
    reviewsCount: 200
  },
  {
    id: 5,
    category: "Рубашки",
    name: "CASUAL BEIGE",
    price: 32,
    inStock: true,
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Бежевый", "Коричневый"],
    image: "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=500",
    description: "Casual рубашка бежевого цвета для расслабленного стиля.",
    material: "100% хлопок",
    care: ["Стирать при 30°C", "Не отбеливать"],
    rating: 4.5,
    reviewsCount: 76
  },
  {
    id: 6,
    category: "Худи",
    name: "HOODIE BLACK",
    price: 45,
    inStock: true,
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Чёрный", "Серый"],
    image: "https://images.unsplash.com/photo-1556821552-5f5f59e4f9f9?w=500",
    description: "Тёплое чёрное худи для холодной погоды.",
    material: "80% хлопок, 20% полиэстер",
    care: ["Стирать при 30°C", "Сушить в горизонтальном положении"],
    rating: 4.7,
    reviewsCount: 189
  },
  {
    id: 7,
    category: "Худи",
    name: "HOODIE NAVY",
    price: 48,
    inStock: true,
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Тёмно-синий", "Чёрный"],
    image: "https://images.unsplash.com/photo-1552856672-f4a45c1ceaea?w=500",
    description: "Тёмно-синее худи с удобным карманом-кенгуру.",
    material: "80% хлопок, 20% полиэстер",
    care: ["Стирать при 30°C", "Вывернуть перед стиркой"],
    rating: 4.8,
    reviewsCount: 210
  },
  {
    id: 8,
    category: "Джинсы",
    name: "SLIM FIT DARK",
    price: 55,
    inStock: true,
    sizes: ["28", "30", "32", "34", "36", "38"],
    colors: ["Тёмно-синий"],
    image: "https://images.unsplash.com/photo-1542272604-787c62d465d1?w=500",
    description: "Классические слим-фит джинсы тёмного цвета.",
    material: "100% хлопок денима",
    care: ["Стирать при 30°C", "Вывернуть перед стиркой", "Не сушить в машине"],
    rating: 4.6,
    reviewsCount: 156
  },
  {
    id: 9,
    category: "Джинсы",
    name: "COMFORT LIGHT",
    price: 50,
    inStock: true,
    sizes: ["28", "30", "32", "34", "36", "38"],
    colors: ["Светло-синий", "Серый"],
    image: "https://images.unsplash.com/photo-1584865288642-42078afe6ff3?w=500",
    description: "Удобные светлые джинсы для повседневного ношения.",
    material: "98% хлопок, 2% эластан",
    care: ["Стирать при 30°C", "Не отбеливать"],
    rating: 4.5,
    reviewsCount: 134
  },
  {
    id: 10,
    category: "Куртки",
    name: "BOMBER BLACK",
    price: 85,
    inStock: true,
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Чёрный"],
    image: "https://images.unsplash.com/photo-1551028719-00167b16ebc5?w=500",
    description: "Стильная чёрная бомбер-куртка для прохладной погоды.",
    material: "Верх: 100% полиэстер, Подкладка: 100% нейлон",
    care: ["Чистить локально", "Не стирать в машине"],
    rating: 4.9,
    reviewsCount: 267
  },
  {
    id: 11,
    category: "Обувь",
    name: "SNEAKER WHITE",
    price: 65,
    inStock: true,
    sizes: ["36", "37", "38", "39", "40", "41", "42", "43", "44", "45"],
    colors: ["Белый"],
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500",
    description: "Классические белые кроссовки для любого стиля.",
    material: "Верх: текстиль и кожа, Подошва: резина",
    care: ["Чистить мягкой щёткой", "Сушить при комнатной температуре"],
    rating: 4.8,
    reviewsCount: 312
  },
  {
    id: 12,
    category: "Аксессуары",
    name: "CAP CLASSIC",
    price: 20,
    inStock: true,
    sizes: ["One Size"],
    colors: ["Чёрный", "Белый", "Серый"],
    image: "https://images.unsplash.com/photo-1584308666744-24d5f400f7d2?w=500",
    description: "Классическая бейсболка для защиты от солнца.",
    material: "100% хлопок",
    care: ["Стирать в холодной воде", "Высушить в горизонтальном положении"],
    rating: 4.4,
    reviewsCount: 98
  },
  {
    id: 13,
    category: "Аксессуары",
    name: "SOCKS PACK",
    price: 15,
    inStock: true,
    sizes: ["35-40", "40-45"],
    colors: ["Ассорти"],
    image: "https://images.unsplash.com/photo-1586350977529-186a87ad8918?w=500",
    description: "Набор из 3 пар комфортных носков.",
    material: "70% хлопок, 25% полиэстер, 5% эластан",
    care: ["Стирать при 40°C", "Не отбеливать"],
    rating: 4.3,
    reviewsCount: 67
  },
  {
    id: 14,
    category: "Аксессуары",
    name: "BELT LEATHER",
    price: 30,
    inStock: true,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Чёрный", "Коричневый"],
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500",
    description: "Кожаный ремень классического стиля.",
    material: "100% натуральная кожа",
    care: ["Чистить сухой тканью", "Избегать влаги", "Наносить кондиционер"],
    rating: 4.7,
    reviewsCount: 123
  }
];

module.exports = products;
